name: 👑 ⚙️ Build Nim Binaries w/ Forge

on:
  workflow_call:

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO: modify to cache .workspace
      # - name: Cache nimble
      #   id: cache-nimble
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.nimble
      #     key: "${{ runner.os }}-nimble-${{ hashFiles('*.nimble', '*.lock') }}"
      #     restore-keys: |
      #       ${{ runner.os }}-nimble-
      
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 2.0.0

      - uses: goto-bus-stop/setup-zig@v2

      - name: Setup Environment
        run: |
          nimble install -Y forge 'https://github.com/nim-lang/atlas@#ab22f9'
          atlas init --deps=.workspace
          atlas install

      - name: Create artifact bundles
        run: |
          nim release
          nim bundle

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/*.tar.gz
            dist/*.zip

