name: ⌛ Check Commits

on:
  workflow_call:
    inputs:
      since:
        type: string
        default: '24 hours'
    outputs:
      quit:
        description: "boolean to quit job"
        value: ${{ jobs.check-commits.outputs.quit }}

jobs:
  check-commits:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      quit: ${{ steps.should_run.outputs.quit }}
    steps:
      - uses: actions/checkout@v5

      - name: print latest commit
        run: echo ${{ github.sha }}

      - id: should_run
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: |
          if [[ "$(git rev-list --since='${{ inputs.since }}' HEAD | wc -l)" -eq 0 ]]; then
            echo "quit=true" >> "$GITHUB_OUTPUT"
          fi

