name: 🚀 Release

on:
  workflow_call:

permissions:
  contents: write

jobs:
  create-release:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

      - run: ls -R artifacts/

      - name: Generate New Release
        run: |
          gh release create ${{ github.ref }} ./artifacts/*
